"""TRICERATOPS+ rewrite: astrophysical false-positive probability calculator."""
from __future__ import annotations

__version__ = "0.2.0.dev0"

from triceratops.config.config import Config, MissionConfig
from triceratops.domain.scenario_id import ScenarioID
from triceratops.validation import (
    ApertureProvenance,
    ApertureConfig,
    ArtifactCapabilities,
    AutoFppComputeConfig,
    AutoFppPrepareConfig,
    AutoFppPreparedField,
    AutoFppPreparedLightCurve,
    AutoFppPreparedTrilegal,
    AutoFppResolvedTarget,
    FilesystemPreparedArtifactStore,
    FppRunConfig,
    FppRunResult,
    PreparedArtifactStore,
    PreparedAutoFppArtifact,
    StoredArtifactRef,
    ValidationEngine,
    ValidationWorkspace,
    assemble_auto_fpp_stellar_field,
    build_auto_fpp_artifact,
    compute_auto_fpp,
    materialize_auto_fpp_trilegal,
    prepare_auto_fpp,
    prepare_auto_fpp_lightcurve,
    resolve_auto_fpp_target,
    run_tess_fpp,
)

__all__ = [
    "__version__",
    "ValidationWorkspace",
    "ValidationEngine",
    "PreparedAutoFppArtifact",
    "ArtifactCapabilities",
    "ApertureProvenance",
    "PreparedArtifactStore",
    "FilesystemPreparedArtifactStore",
    "StoredArtifactRef",
    "ApertureConfig",
    "AutoFppPrepareConfig",
    "AutoFppComputeConfig",
    "AutoFppResolvedTarget",
    "AutoFppPreparedLightCurve",
    "AutoFppPreparedField",
    "AutoFppPreparedTrilegal",
    "FppRunConfig",
    "FppRunResult",
    "resolve_auto_fpp_target",
    "prepare_auto_fpp_lightcurve",
    "assemble_auto_fpp_stellar_field",
    "materialize_auto_fpp_trilegal",
    "build_auto_fpp_artifact",
    "prepare_auto_fpp",
    "compute_auto_fpp",
    "run_tess_fpp",
    "Config",
    "MissionConfig",
    "ScenarioID",
]
